#!/bin/bash

echo "======================================"
echo "REFACTORING: VF → NF (NiroForge)"
echo "======================================"
echo ""
echo "Renaming all VisualForge (instance) references to NiroForge (product)"
echo ""

echo "=== LAMBDA FUNCTIONS ==="
echo "Current VF Name -> New NF Name:"
echo ""
echo "Core NiroForge Functions:"
echo "  dev-visualforge-core           -> nf-core"
echo "  dev-vf-dashboard-lambda        -> nf-dashboard"
echo "  dev-vf-auth-lambda             -> nf-auth"
echo "  dev-vf-image-lambda            -> nf-image"
echo "  dev-vf-video-lambda            -> nf-video"
echo "  dev-vf-audio-lambda            -> nf-audio"
echo "  dev-vf-text-lambda             -> nf-text"
echo "  dev-vf-bulk-lambda             -> nf-bulk"
echo "  dev-visualforge-budgets-api    -> nf-budgets-api"
echo "  dev-visualforge-costs-api      -> nf-costs-api"
echo "  dev-visualforge-payments-api   -> nf-payments-api"
echo "  dev-visualforge-user-api       -> nf-user-api"
echo "  dev-visualforge-dashboard-api  -> nf-dashboard-api"
echo "  dev-visualforge-test-jwks      -> nf-test-jwks"
echo "  dev-visualforge-init-db        -> nf-init-db"
echo "  dev-visualforge-create-tables  -> nf-create-tables"
echo "  dev-visualforge-debug-db       -> nf-debug-db"
echo "  dev-visualforge-update-user    -> nf-update-user"
echo ""

echo "=== DYNAMODB TABLES ==="
echo "Current VF Name -> New NF Name:"
echo "  dev-vf-media                   -> nf-media"
echo "  dev-vf-users                   -> nf-users"
echo "  dev-visualforge-budget-config  -> nf-budget-config"
echo "  dev-visualforge-tenant-costs   -> nf-tenant-costs"
echo "  vf-ai-generations-dev          -> nf-ai-generations"
echo "  vf-media-items-dev             -> nf-media-items"
echo "  vf-projects-dev                -> nf-projects"
echo "  vf-subscriptions-dev           -> nf-subscriptions"
echo ""

echo "=== API GATEWAYS ==="
echo "  dev-visualforge-api            -> nf-api"
echo ""

echo "=== CLOUDFORMATION STACKS ==="
echo "  dev-vf-serverless-stack        -> nf-serverless-stack"
echo "  dev-visualforge-database       -> nf-database"
echo "  vf-media-*                     -> nf-media-*"
echo ""

echo "=== S3 BUCKETS (if any) ==="
echo "  vf-* buckets                   -> nf-* buckets"
echo ""

echo "======================================"
echo "ARCHITECTURE AFTER REFACTORING:"
echo "======================================"
echo ""
echo "NiroForge Platform (NF):"
echo "  • nf-core"
echo "  • nf-dashboard"
echo "  • nf-auth"
echo "  • nf-media"
echo "  • nf-[services]"
echo ""
echo "NiroSubs Subsystem (NS):"
echo "  • ns-payments"
echo "  • ns-subscriptions"
echo "  • ns-billing"
echo ""
echo "General/Admin (NA):"
echo "  • na-monitoring"
echo "  • na-secrets"
echo ""
echo "Instance Branding (Config Only):"
echo "  • BRAND_NAME=VisualForge"
echo "  • INSTANCE_ID=visualforge"
echo "  • Custom themes/logos via config"
echo ""